DT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('Homepage.urls')),
    path('host/', include('Host.urls')),
    path('company/', include('Company.urls')),
    path('sales/', include('Sales.urls')),
    path('dispatcher/', include('Dispatcher.urls')),
    path('driver/', include('Driver.urls'))
]

Homepage/urls.py
from django.urls import path

from . import views

app_name = 'Homepage_app'

urlpatterns = [
   path('', views.Homepage_page.as_view(), name = 'Homepage_homepage'),
   path('login/', views.login.as_view(), name = 'Homepage_login'),
   path('search-order/<str:code_order>/', views.Search_order.as_view(), name ='Homepage_search_order')
]

Sales/urls.py
from django.urls import path

from . import views 

app_name = 'Sales_app'

urlpatterns = [
    path('get-all-province/', views.get_all_province, name = 'Sales_get_all_province'),
    path('get-all-district/', views.get_district_by_province, name = 'Sales_get_all_district'),
    path('get-all-ward/', views.get_ward_by_district_province, name = 'Sales_get_all_ward'),
    path('', views.Homepage.as_view(), name = 'Sales_homepage' ),
    path('customer/', views.Customer.as_view(), name='Sales_customer'),
    path('customer/add-new/', views.Add_new_customer.as_view(), name='Sales_add_new_customer'),
    path('customer/show-all/', views.Show_all_customer.as_view(), name = 'Sales_show_all_customer'),
    path('customer/update-status-customer/', views.Update_status_customer.as_view(), name = 'Sales_update_status_customer'),
    path('contract/', views.Contract.as_view(), name='Sales_contract'),
    path('account/', views.Account.as_view(), name = 'Sales_account'),
    path('log_out/', views.log_out, name = 'Sales_log_out')
]

Sales/models.py
from django.db import models

# Create your models here.

Homepage/views.py
from django.shortcuts import render, redirect
from django.views import View
import datetime
import hashlib
import os
import base64
from dotenv import load_dotenv
import jwt


from . import exec_data

# Create your views here. 
class Homepage_page(View):
    def get(self, request):
        return render(request, 'Homepage/homepage.html')
    def post(self, request):
        get_code_order = request.POST.get('pre_header_search', None)
        return redirect('Homepage_app:Homepage_search_order', code_order = get_code_order)

class login(View):
    def get(self, request):
        return render(request, 'Homepage/login.html')
    def post(self, request):
        load_dotenv()
        secret_key = os.getenv('secret_key')
        salt_key = os.getenv('salt_key')

        request.session.clear()

        role_select = request.POST.get('login_choose_role', None)
        get_username = request.POST.get('user_name_login', None)
        get_password = request.POST.get('pass_login', None)

        exec_check_login = exec_data.check_login_pass_username(role_select, get_username, get_password, salt_key)
        
        if (exec_check_login != False) and (len(exec_check_login) == 1):
            start_time_token = datetime.datetime.now().strftime(f'%d-%m-%Y %H:%M:%S')
            end_time_token = (datetime.datetime.now() + datetime.timedelta(days = 2)).strftime(f'%d-%m-%Y %H:%M:%S')

            dict_token = {'role_user' : role_select, 'id_role_user' : exec_check_login[0]['id'], 'start_time' : start_time_token, 'end_time' : end_time_token}

            request.session['token_dt2023_web_demo'] = jwt.encode(dict_token, secret_key, algorithm='HS256')
            request.session['role_user_dt2023'] = role_select
            request.session['id_role_user_dt2023'] = exec_check_login[0]['id']

            if role_select == 'driver':
                return redirect('Driver_app:Driver_base_page')
            elif role_select == 'company':
                return redirect('Company_app:Company_homepage') 
            elif role_select == 'sale':
                return redirect('Sales_app:Sales_homepage')
            elif role_select == 'dispatcher':
                return redirect('Dispatcher_app:Dispatcher_homepage')
            elif role_select == 'host':
                return redirect('Host_app:Host_base_page')
        else:
            return render(request, 'Homepage/login.html', {'notification_login' : 'Đăng nhập thất bại. Xem lại mật khẩu và tên đăng nhập'})

        return render(request, 'Homepage/login.html')

class Search_order(View):
    def get(self, request, code_order):
        result_search_order = exec_data.get_order_by_code_order(code_order)
        if result_search_order != False and len(result_search_order) == 0:
            result_search_order = []

        context_return = {}
        context_return['code_order'] = code_order
        context_return['result_search_order'] = result_search_order

        return render(request, 'Homepage/search_order.html', context_return)

Sales/views.py
from dotenv import load_dotenv
import os
import jwt 
import datetime 

from django.shortcuts import render, redirect
from django.views import View 
from django.http import JsonResponse

from . import exec_data

# Create your views here.
# This function try to check token. If token already is use. It continue browsing or redirect to homepage
def check_login_required(token_str):
    load_dotenv()
    secret_key = os.getenv('secret_key')
    decode_token = jwt.decode(token_str, secret_key, algorithms = ["HS256"])
    current_time = datetime.datetime.now()
    end_time_token = datetime.datetime.strptime(decode_token['end_time'], f'%d-%m-%Y %H:%M:%S')
    if current_time < end_time_token:
        role_user_temp = decode_token['role_user']
        if role_user_temp == 'sale':
            return True
        else:
            return 'NP'
    else:
        return 'ET'

# 3 function help to load and get division
def get_all_province(request):
    # Check token
    full_token_str = request.session.get('token_dt2023_web_demo', None)
    if full_token_str is None or full_token_str == '':
        return redirect('Homepage_app:Homepage_homepage')
    check_token_str = check_login_required(full_token_str)
    if check_token_str != True:
        return redirect('Homepage_app:Homepage_homepage')
    # End check token string

    get_all_province = exec_data.get_all_province()
    lst_all_province_temp = [item['province'] for item in get_all_province]
    dict_all_province = {'result' : lst_all_province_temp}
    return JsonResponse(dict_all_province)
    
def get_district_by_province(request):
    # Check token
    full_token_str = request.session.get('token_dt2023_web_demo', None)
    if full_token_str is None or full_token_str == '':
        return redirect('Homepage_app:Homepage_homepage')
    check_token_str = check_login_required(full_token_str)
    if check_token_str != True:
        return redirect('Homepage_app:Homepage_homepage')
    # End check token string

    name_province = request.POST.get('province', None)
    get_all_district = exec_data.get_all_district_by_name_province(name_province)
    lst_all_district = [item['district'] for item in get_all_district]
    dict_all_district = {'result' : lst_all_district}
    return JsonResponse(dict_all_district)

def get_ward_by_district_province(request):
    # Check token
    full_token_str = request.session.get('token_dt2023_web_demo', None)
    if full_token_str is None or full_token_str == '':
        return redirect('Homepage_app:Homepage_homepage')
    check_token_str = check_login_required(full_token_str)
    if check_token_str != True:
        return redirect('Homepage_app:Homepage_homepage')
    # End check token string

    name_province = request.POST.get('province', None)
    name_district = request.POST.get('district', None)
    get_all_ward = exec_data.get_all_ward_by_name_province_name_district(name_province, name_district)
    lst_all_ward = [item['ward'] for item in get_all_ward]
    dict_all_ward = {'result' : lst_all_ward}
    return JsonResponse(dict_all_ward)

def log_out(request):
    request.session.clear()
    return redirect('Homepage_app:Homepage_homepage')

class Homepage(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string
        
        return render(request, 'Sales/homepage.html')

class Customer(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Sales/tab_customer.html')

class Add_new_customer(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Sales/tab_customer_add_new.html')
    def post(self, request):
        # TODO  : thinking có nên add check token
        new_gmail = request.POST.get('new_customer_gmail', None)
        new_tel = request.POST.get('new_customer_tel', None)
        new_province = request.POST.get('new_customer_province', None)
        new_district = request.POST.get('new_customer_district', None)
        new_ward = request.POST.get('new_customer_ward', None)
        new_full_name = request.POST.get('new_customer_full_name', None)
        new_gender = request.POST.get('new_customer_gender', None)
        new_type = request.POST.get('new_customer_type', None)
        new_status = request.POST.get('new_customer_status', None)

        return_para = {'new_gmail_para' : new_gmail, 'new_tel_para' : new_tel, 'new_province_para' : new_province, 'new_district_para' : new_district, 'new_ward_para' : new_ward, 'new_full_name_para' : new_full_name, 'new_gender_para' : new_gender, 'new_type_para' : new_type, 'new_status_para' : new_status}
        ins_new_customer = exec_data.add_new_customer(**return_para)

        context_return = {}
        if ins_new_customer == True:
            context_return['ins_new_customer'] = 'Thêm khách hàng mới thành công'
        else:
            context_return['ins_new_customer'] = 'Thêm khách hàng mới thất bại'

        return render(request, 'Sales/tab_customer_add_new.html', context_return)
    
class Show_all_customer(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_sales = request.session.get('id_role_user_dt2023', None)
        context_return = {}
        get_all_customer = exec_data.get_all_customer_by_id_sale(id_sales)

        if get_all_customer != False:
            context_return['all_customer'] = get_all_customer

        return render(request, 'Sales/tab_customer_show_all.html', context_return)
    
class Update_status_customer(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Sales/tab_customer_update_status.html')
    def post(self, request):
        context_return = {}

        get_id_customer = request.POST.get('search_id_customer', None)
        get_status_update = request.POST.get('select_status_customer', None)

        update_status = exec_data.update_status_customer(get_id_customer, get_status_update)

        if update_status == True:
            context_return['update_status_message'] = 'Cập nhật thành công'
        else:
            context_return['update_status_message'] = 'Cập nhật thất bại'
        
        return render(request, 'Sales/tab_customer_update_status.html', context_return)

class Contract(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string
    
        id_sales = request.session.get('id_role_user_dt2023', None)
        all_customer = exec_data.get_all_customer_by_id_sale(id_sales)

        return render(request, 'Sales/tab_contract.html', {'all_customer' : all_customer})

    def post(self, request):
        id_sales = request.session.get('id_role_user_dt2023', None)
        all_customer = exec_data.get_all_customer_by_id_sale(id_sales)

        new_start_time = request.POST.get('input_start_time_contract', None)
        new_end_time =  request.POST.get('input_end_time_contract', None)
        new_date_sign = request.POST.get('input_date_sign_contract', None)
        new_cost = request.POST.get('input_cost_contract', None)
        new_url_scan = request.POST.get('input_url_contract', None)
        new_note = request.POST.get('input_note_contract', None)
        new_id_customer = request.POST.get('input_id_customer', None)

        return_para = {'id_sale_para' : id_sales, 'id_customer_para' : new_id_customer, 'start_time_para' : new_start_time, 'end_time_para' : new_end_time, 'date_sign_para' : new_date_sign, 'cost_para' : new_cost, 'link_drive_scan_para' : new_url_scan, 'note_para' : new_note}
        ins_new_contract = exec_data.ins_new_contract(**return_para)

        return render(request, 'Sales/tab_contract.html', {'all_customer' : all_customer})
        
class Account(View):
    def get(self,request):

Sales/templates/Sales/homepage.html
{% load static %}

<link rel="stylesheet" href="{% static 'Sales/css/homepage.css' %}">

{% block sales_content_page %}

{% endblock %}
<!-- Button ở dưới cùng -->
<div class="group__btn__tab">
    <a class="btn__tab__link" href="{% url 'Sales_app:Sales_homepage' %}" id="default__open__tab">Information</a>
    <a class="btn__tab__link" href="{% url 'Sales_app:Sales_account' %}" id="open__account__tab">Account</a>
    <a class="btn__tab__link" href="{% url 'Sales_app:Sales_customer' %}" id="open__customer__tab">Customer</a>
    <a class="btn__tab__link" href="{% url 'Sales_app:Sales_contract' %}" id="open__contract__tab">Contract</a>
    <a class="btn__tab__link" href="#">History</a>
</div>
<!-- Kết thúc các nút -->

Sales/templates/Sales/tab_account.html
{% extends 'Sales/homepage.html' %}
{% load static %}

{% block sales_content_page %}
    <div class="tab__content" id="tab__account">
        <a href="{% url 'Sales_app:Sales_log_out' %}">Log out</a>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            let all_tab = document.getElementsByClassName('btn__tab__link')
            
            for ( let index = 0; index < all_tab.length; index ++){
                all_tab[index].style.backgroundColor = '#555'
            }
            document.getElementById('open__account__tab').style.backgroundColor = 'orange'
        })
    </script>
{% endblock %}

Sales/templates/Sales/tab_contract.html
{% extends 'Sales/homepage.html' %}
{% load static %}

{% block sales_content_page %}
    <link rel="stylesheet" href="{% static 'Sales/css/tab_contract.css' %}">
    <div class="tab__content" id="tab__contract">
        <form method="post">
            {% csrf_token %}
            <div class="tab__contract__title">
                <h1>New Contract</h1>
                <input type="submit" value="Add New">
            </div><hr><br>
            <div class="tab__contract-item">
                <label>Start time :</label>
                <input type="datetime-local" name="input_start_time_contract">
            </div>
            <div class="tab__contract-item">
                <label>End Time :</label>
                <input type="datetime-local" name="input_end_time_contract">
            </div>
            <div class="tab__contract-item">
                <label>Date Sign :</label>
                <input type="datetime-local" name="input_date_sign_contract">
            </div>
            <div class="tab__contract-item">
                <label>Cost :</label>
                <input type="tel" name="input_cost_contract">
            </div>
            <div class="tab__contract-item">
                <label>Link Driver Scan :</label>
                <input type="url" name="input_url_contract">
            </div>
            <div class="tab__contract-item">
                <label>Note :</label>
                <textarea name="input_note_contract"></textarea>
            </div>
            <div class="tab__contract-item">
                <label>Choose Customer :</label>
                <select name="input_id_customer">   
                    <option value="None">Choose Customer</option>
                    {% for customer in all_customer %}
                        <option value="{{customer.id}}">{{customer.full_name}}</option>
                    {% endfor %}
                </select>
            </div>
        </form>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            let all_tab = document.getElementsByClassName('btn__tab__link')
            
            for ( let index = 0; index < all_tab.length; index ++){
                all_tab[index].style.backgroundColor = '#555'
            }
            document.getElementById('open__contract__tab').style.backgroundColor = 'blue'
        })
    </script>
{% endblock %}

Sales/templates/Sales/tab_customer.html
{% extends 'Sales/homepage.html' %}
{% load static %}

{% comment %}{% static 'Sales/javascript/tab_customer.js' %}{% endcomment %}
{% block sales_content_page %}
    <div class="option__tab__customer">
        <a class="option__tab__customer-item" href="{% url 'Sales_app:Sales_add_new_customer' %}">Add new customer</a>
        <a class="option__tab__customer-item" href="{% url 'Sales_app:Sales_show_all_customer' %}">Show all customer</a>
        <a class="option__tab__customer-item" href="{% url 'Sales_app:Sales_update_status_customer' %}">Update Status</a>
    </div>
    <link rel="stylesheet" href="{% static 'Sales/css/tab_customer.css' %}">
    <div class="tab__content" id="tab__customer">
        {% block tab_customer_content %}

        {% endblock %}
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            let all_tab = document.getElementsByClassName('btn__tab__link')
            
            for ( let index = 0; index < all_tab.length; index ++){
                all_tab[index].style.backgroundColor = '#555'
            }
            document.getElementById('open__customer__tab').style.backgroundColor = 'green'
        })
    </script>
{% endblock %}

Sales/templates/Sales/tab_customer_add_new.html
{% extends 'Sales/tab_customer.html' %}
{% load static %}

{% block tab_customer_content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="{% static 'Sales/javascript/load_division.js' %}"></script>
    <script>
        document.onreadystatechange = function(){
            if (document.readyState === 'interactive') {
                on_load_province();
            }
        } 
    </script>

    {% if ins_new_customer %}
        <div>
            <p>{{ins_new_customer}}</p>
        </div>
    {% endif %}
    <div class="tab__customer-item__content">
        <form method="post">
            {% csrf_token %}
            <div class="form__inner">
                <div class="add__customer-item">
                    <label>Gmail :</label>
                    <input type="text" name="new_customer_gmail">
                </div>
                <div class="add__customer-item">
                    <label>Telephone :</label>
                    <input type="tel" name="new_customer_tel">
                </div>
                <div class="add__customer-item add__customer__division">
                    <div>
                        <label>Province :</label>
                        <select name="new_customer_province" id="choose__province__new__customer" class="new__province__customer__select" onchange="load_district()">
                            <option value="None" selected>Chọn tỉnh</option>
                        </select>
                    </div>
                    <div>
                        <label>District :</label> 
                        <select name="new_customer_district" id="choose__district__new__customer" onchange="load_ward()">
                            <option value="None" selected>Chọn huyện</option>
                        </select>  
                    </div>
                    <div>
                        <label>Ward :</label>
                        <select name="new_customer_ward" id="choose__ward__new__customer">
                            <option value="None" selected>Chọn xã</option>
                        </select>
                    </div>
                </div>
                <div class="add__customer-item">
                    <label>Full name :</label>
                    <input type="text" name="new_customer_full_name">
                </div>
                <div class="add__customer-item">
                    <label>Gender</label>
                    <select name="new_customer_gender">
                        <option value="None">Choose Gender</option>
                        <option value="1">Men</option>
                        <option value="2">Woman</option>
                        <option value="3">Other</option>
                    </select>
                </div>
                <div class="add__customer-item">
                    <label>Type :</label>
                    <select name="new_customer_type">
                        <option value="None">Choose Type :</option>
                        <option value="personal">Personal</option>
                        <option value="company">Company</option>
                    </select>
                </div>
                <div class="add__customer-item">
                    <label>Status</label>
                    <select name="new_customer_status">
                        <option value="None">Choose Status:</option>
                        <option value="flow">Flow</option>
                        <option value="meeting">Meeting</option>
                        <option value="pending">Pending</option>
                        <option value="signoff">Signoff</option>
                        <option value="recheck">Recheck</option>
                    </select>
                </div>
            </div>
            <input type="submit" name="add_new_customer_submit" value="Add" id="submit__add__new__customer">
        </form>
    </div>
{% endblock %}

Sales/templates/Sales/tab_customer_show_all.html
{% extends 'Sales/tab_customer.html' %}
{% load static %}

{% block tab_customer_content %}
    <link rel="stylesheet" href="{% static 'Sales/css/tab_customer.css' %}">
    <table>
        <tr>
            <th>No.</th>
            <th>ID Customer</th>
            <th>Gmail</th>
            <th>Telephone</th>
            <th>Full Name</th>
            <th>Gender</th>
            <th>Type</th>
            <th>Status</th>
        </tr>
        {% for customer in all_customer %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{customer.id_customer}}</td>
                <td>{{customer.gmail}}</td>
                <td>{{customer.tel}}</td>
                <td>{{customer.full_name}}</td>
                <td>{{customer.gender}}</td>
                <td>{{customer.types}}</td>
                <td>{{customer.status}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

Sales/templates/Sales/tab_customer_update_status.html
{% extends 'Sales/tab_customer.html' %}
{% load static %}

{% block tab_customer_content %}
    {% if update_status_message %}
        <div>
            <p>{{update_status_message}}</p>
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <label>Input ID Customer :</label>
        <input type="text" name = "search_id_customer">
        <select name="select_status_customer">
            <option value="None">Choose Status</option>
            <option value="flow">Flow</option>
            <option value="meeting">Meeting</option>
            <option value="pending">Pending</option>
            <option value="signoff">Signoff</option>
            <option value="recheck">Recheck</option>
        </select>
        <input type="submit">
    </form>
{% endblock %}

Sales/templates/Sales/tab_history.html
<div class="tab__content" id="tab__history">

</div>