Company/urls.py
from django.urls import path

from . import views

app_name = 'Company_app'

urlpatterns = [
    path('', views.Homepage.as_view(), name = 'Company_homepage'),
    path('sales/', views.Sales.as_view(), name = 'Company_sales'),
    path('dispatcher/', views.Dispatcher.as_view(), name = 'Company_dispatcher'),
    path('driver/', views.Driver.as_view(), name='Company_driver'),
    path('get-all-province/', views.get_all_province, name = 'Company_get_all_province'),
    path('get-all-district/', views.get_district_by_province, name = 'Company_get_all_district'),
    path('get-all-ward/', views.get_ward_by_district_province, name = 'Company_get_all_ward'),
    path('log-out/', views.log_out, name = 'Company_log_out')
]

DT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('Homepage.urls')),
    path('host/', include('Host.urls')),
    path('company/', include('Company.urls')),
    path('sales/', include('Sales.urls')),
    path('dispatcher/', include('Dispatcher.urls')),
    path('driver/', include('Driver.urls'))
]

Driver/urls.py
from django.urls import path

from . import views 

app_name = 'Driver_app'

urlpatterns = [
    path('', views.Base_page.as_view(), name = 'Driver_base_page'),
    path('log-out/', views.log_out, name = 'Driver_log_out'),
    path('order-need-delivery/', views.Order_need_delivery.as_view(), name = 'Driver_order_need_delivery'),
    path('update-status-order/', views.Update_status_order.as_view(), name='Driver_update_status_order'),
    path('order-in-delivery/', views.Order_in_delivery.as_view(), name='Driver_order_in_delivery'),
    path('order-success/', views.Order_success.as_view(), name='Driver_order_success')
]

Sales/urls.py
from django.urls import path

from . import views 

app_name = 'Sales_app'

urlpatterns = [
    path('get-all-province/', views.get_all_province, name = 'Sales_get_all_province'),
    path('get-all-district/', views.get_district_by_province, name = 'Sales_get_all_district'),
    path('get-all-ward/', views.get_ward_by_district_province, name = 'Sales_get_all_ward'),
    path('', views.Homepage.as_view(), name = 'Sales_homepage' ),
    path('customer/', views.Customer.as_view(), name='Sales_customer'),
    path('customer/add-new/', views.Add_new_customer.as_view(), name='Sales_add_new_customer'),
    path('customer/show-all/', views.Show_all_customer.as_view(), name = 'Sales_show_all_customer'),
    path('customer/update-status-customer/', views.Update_status_customer.as_view(), name = 'Sales_update_status_customer'),
    path('contract/', views.Contract.as_view(), name='Sales_contract'),
    path('account/', views.Account.as_view(), name = 'Sales_account'),
    path('log_out/', views.log_out, name = 'Sales_log_out')
]

Company/models.py
from django.db import models

# Create your models here.

Dispatcher/models.py
from django.db import models

# Create your models here.

Driver/models.py
from django.db import models

# Create your models here.

Sales/models.py
from django.db import models

# Create your models here.

Company/views.py
import os
from dotenv import load_dotenv
import jwt 
import datetime 

from django.shortcuts import render, redirect
from django.views import View 
from django.http import JsonResponse
from dotenv import load_dotenv

from . import exec_data

# Create your views here.
# This function try to check token. If token already is use. It continue browsing or redirect to homepage
def check_login_required(token_str):
    load_dotenv()
    secret_key = os.getenv('secret_key')
    decode_token = jwt.decode(token_str, secret_key, algorithms = ["HS256"])
    current_time = datetime.datetime.now()
    end_time_token = datetime.datetime.strptime(decode_token['end_time'], f'%d-%m-%Y %H:%M:%S')
    if current_time < end_time_token:
        role_user_temp = decode_token['role_user']
        if role_user_temp == 'company':
            return True
        else:
            return 'NP'
    else:
        return 'ET'

def log_out(request):
    request.session.clear()
    return redirect('Homepage_app:Homepage_homepage')

# 3 function help to load and get division
def get_all_province(request):
    # Check token
    full_token_str = request.session.get('token_dt2023_web_demo', None)
    if full_token_str is None or full_token_str == '':
        return redirect('Homepage_app:Homepage_homepage')
    check_token_str = check_login_required(full_token_str)
    if check_token_str != True:
        return redirect('Homepage_app:Homepage_homepage')
    # End check token string

    get_all_province = exec_data.get_all_province()
    lst_all_province_temp = [item['province'] for item in get_all_province]
    dict_all_province = {'result' : lst_all_province_temp}
    return JsonResponse(dict_all_province)
    
def get_district_by_province(request):
    # Check token
    full_token_str = request.session.get('token_dt2023_web_demo', None)
    if full_token_str is None or full_token_str == '':
        return redirect('Homepage_app:Homepage_homepage')
    check_token_str = check_login_required(full_token_str)
    if check_token_str != True:
        return redirect('Homepage_app:Homepage_homepage')
    # End check token string

    name_province = request.POST.get('province', None)
    get_all_district = exec_data.get_all_district_by_name_province(name_province)
    lst_all_district = [item['district'] for item in get_all_district]
    dict_all_district = {'result' : lst_all_district}
    return JsonResponse(dict_all_district)

def get_ward_by_district_province(request):
    # Check token
    full_token_str = request.session.get('token_dt2023_web_demo', None)
    if full_token_str is None or full_token_str == '':
        return redirect('Homepage_app:Homepage_homepage')
    check_token_str = check_login_required(full_token_str)
    if check_token_str != True:
        return redirect('Homepage_app:Homepage_homepage')
    # End check token string

    name_province = request.POST.get('province', None)
    name_district = request.POST.get('district', None)
    get_all_ward = exec_data.get_all_ward_by_name_province_name_district(name_province, name_district)
    lst_all_ward = [item['ward'] for item in get_all_ward]
    dict_all_ward = {'result' : lst_all_ward}
    return JsonResponse(dict_all_ward)

class Homepage(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Company/homepage.html')

class Sales(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Company/sale.html')
    def post(self, request):
        load_dotenv()
        salt_key = os.getenv('salt_key')

        id_company = request.session.get('id_role_user_dt2023', None)

        new_user_name = request.POST.get('new_sale_username', None)
        new_password = request.POST.get('new_sale_password', None)
        new_gmail = request.POST.get('new_sale_gmail', None)
        new_tel = request.POST.get('new_sale_tel', None)
        new_gender = request.POST.get('new_sale_gender', None)
        new_province = request.POST.get('new_sale_province', None)
        new_district = request.POST.get('new_sale_district', None)
        new_ward = request.POST.get('new_sale_ward')

        return_para = {'username_para' : new_user_name, 'password_para' : new_password, 'gmail_para' : new_gmail, 'tel_para' : new_tel, 'gender_para' : new_gender, 'province_para' : new_province, 'district_para' : new_district, 'ward_para' : new_ward, 'salt_key' : salt_key, 'id_company_para' : id_company}
        ins_new_sale = exec_data.ins_new_sale(**return_para)

        context_return = {}
        if ins_new_sale != False:
            context_return['ins_sale_mess'] = 'Thêm 1 sale mới thành công'
        else:
            context_return['ins_sale_mess'] = 'Thêm 1 sale thất bại'

        return render(request, 'Company/sale.html', context_return)

class Dispatcher(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Company/dispatcher.html')
    def post(self, request):
        load_dotenv()
        salt_key = os.getenv('salt_key')

        id_company = request.session.get('id_role_user_dt2023', None)

        new_username = request.POST.get('username_new_dispatcher', None)
        new_password = request.POST.get('password_new_dispatcher', None)
        new_gmail = request.POST.get('gmail_new_dispatcher', None)
        new_tel = request.POST.get('tel_new_dispatcher', None)
        new_gender = request.POST.get('gender_new_dispatcher', None)
        new_province = request.POST.get('province_new_dispatcher', None)
        new_district = request.POST.get('district_new_dispatcher', None)
        new_ward = request.POST.get('ward_new_dispatcher', None)

        return_para = {'id_company_para' : id_company, 'user_name_para' : new_username, 'password_para' : new_password, 'gmail_para' : new_gmail, 'tel_para' : new_tel, 'gender_para' : new_gender, 'province_para' : new_province, 'district_para' : new_district, 'ward_para' : new_ward, 'salt_key' : salt_key}

        ins_new_dispatcher = exec_data.ins_new_dispatcher(**return_para)
        context_return = {}

        if ins_new_dispatcher == True:
            context_return['new_dispatcher'] = True 
        else:
            context_return['new_dispatcher'] = False 

        return render(request, 'Company/dispatcher.html', context_return)

class Driver(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Company/driver.html')

    def post(self, request):
        context_return = {}

        load_dotenv()
        salt_key = os.getenv('salt_key')

        id_company = request.session.get('id_role_user_dt2023', None)

        new_username = request.POST.get('input_new_username', None)
        new_password = request.POST.get('input_new_pass', None)
        new_full_name = request.POST.get('input_new_full_name', None)
        new_gmail = request.POST.get('input_new_gmail', None)
        new_tel = request.POST.get('input_new_tel', None)
        new_province = request.POST.get('select_new_province', None)
        new_district = request.POST.get('select_new_district', None)
        new_ward = request.POST.get('select_new_ward', None)
        new_gender = request.POST.get('ins_new_gender', None)
        new_level_license = request.POST.get('ins_new_level_license', None)

        return_para = {'id_company_para' : id_company, 'username_para' : new_username, 'pass_para' : new_password, 'full_name_para' : new_full_name, 'gmail_para' : new_gmail, 'tel_para' : new_tel, 'province_para' : new_province, 'district_para' : new_district, 'ward_para' : new_ward, 'gender_para' : new_gender, 'level_license_para' :  new_level_license, 'salt_key' : salt_key} 
        ins_new_driver = exec_data.ins_new_driver(**return_para)

        if ins_new_driver == True:
            context_return['new_driver'] = True 
        else:
            context_return['new_driver'] = False 

        return render(request, 'Company/driver.html', context_return)

Driver/views.py
from dotenv import load_dotenv
import os
import jwt 
import datetime 

from django.shortcuts import render, redirect
from django.views import View 

from . import exec_data
# Create your views here.
# This function try to check token. If token already is use. It continue browsing or redirect to homepage
def check_login_required(token_str):
    load_dotenv()
    secret_key = os.getenv('secret_key')
    decode_token = jwt.decode(token_str, secret_key, algorithms = ["HS256"])
    current_time = datetime.datetime.now()
    end_time_token = datetime.datetime.strptime(decode_token['end_time'], f'%d-%m-%Y %H:%M:%S')
    if current_time < end_time_token:
        role_user_temp = decode_token['role_user']
        if role_user_temp == 'driver':
            return True
        else:
            return 'NP'
    else:
        return 'ET'

def log_out(request):
    request.session.clear()
    return redirect('Homepage_app:Homepage_homepage')

class Base_page(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Driver/base_page.html')

class Order_need_delivery(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_driver = request.session.get('id_role_user_dt2023', None)
        
        all_order_need_delivery = exec_data.get_all_order_need_delivery(id_driver)
        context_return = {'all_order_need_delivery' : all_order_need_delivery}
        return render(request, 'Driver/order_need_delivery.html', context_return)

class Update_status_order(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Driver/update_status_order.html')
    def post(self, request):
        get_code_order = request.POST.get('input_code_order', None)
        get_status_update = request.POST.get('select_status_order', None)

        context_return = {}
        update_status_order = exec_data.update_status_order_by_code_order(get_code_order, get_status_update)

        if update_status_order == True:
            context_return['notification_update_status'] = True
            context_return['msg_update_status'] = f'Cập nhật đơn hàng "{get_code_order}" với trạng thái "{get_status_update}" thành công'
        else:
            context_return['notification_update_status'] = False
            context_return['msg_update_status'] = f'Cập nhật đơn hàng "{get_code_order}" với trạng thái "{get_status_update}" thất bại'
        return render(request, 'Driver/update_status_order.html', context_return)

class Order_in_delivery(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_driver = request.session.get('id_role_user_dt2023', None)

        all_order_in_delivery = exec_data.get_all_order_in_delivery(id_driver)
        context_return = {'all_order_in_delivery' : all_order_in_delivery}
        return render(request, 'Driver/order_in_delivery.html', context_return)

class Order_success(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_driver = request.session.get('id_role_user_dt2023', None)

        all_order_success = exec_data.get_all_order_success(id_driver)
        context_return = {'all_order_success' : all_order_success}
        return render(request, 'Driver/order_success.html', context_return)

Company/templates/Company/dispatcher.html
{% extends 'Company/homepage.html' %}
{% load static %}

{% block content_company_page %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="{% static 'Company/javascript/load_division.js' %}"></script>
    <script>
        document.onreadystatechange = function(){
            if (document.readyState === 'interactive') {
                on_load_province();
            }
        } 
    </script>

    <link rel="stylesheet" href="{% static 'Company/css/dispatcher.css' %}">
    {% if new_dispatcher == True %}
        <div class="notification__new__dispatcher">
            <p>Tạo dispatcher mới thành công</p>
        </div>
    {% elif new_dispatcher == False %}
        <div class="notification__new__dispatcher">
            <p>Tạo dispatcher mới thất bại</p>
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="new__dispatcher__title">
            <h1>Add New Dispatcher</h1>
            <input type="submit" value="Add New">
        </div><hr>
        <div class="new__dispatcher__item">
            <label>User Name :</label>
            <input type="text" name="username_new_dispatcher">
        </div>
        <div class="new__dispatcher__item">
            <label>Password :</label>
            <input type="password" name="password_new_dispatcher">
        </div>
        <div class="new__dispatcher__item">
            <label>Gmail :</label>
            <input type="text" name="gmail_new_dispatcher">
        </div>
        <div class="new__dispatcher__item">
            <label>Telephone :</label>
            <input type="tel" name="tel_new_dispatcher">
        </div>
        <div class="new__dispatcher__item">
            <label>Gender :</label>
            <select name="gender_new_dispatcher">
                <option value="None">Choose Gender</option>
                <option value="men">Men</option>
                <option value="woman">Woman</option>
                <option value="other">Other</option>
            </select>   
        </div>
        <div class="new__dispatcher__item new__dispatcher__division">
            <div>
               <label>Province :</label> 
               <select name="province_new_dispatcher" id="choose__province__new__dispatcher" class="new__province__dispatcher__select" onchange="load_district()">
                    <option value="None">Choose Province</option>
               </select>
            </div>
            <div>
                <label>District :</label>
                <select name="district_new_dispatcher" id="choose__district__new__dispatcher" onchange="load_ward()">
                    <option value="None">Choose District</option>
                </select>
            </div>
            <div>
                <label>Ward :</label>
                <select name="ward_new_dispatcher" id="choose__ward__new__dispatcher">
                    <option value="None">Choose Ward</option>
                </select>
            </div>
        </div>
    </form>
{% endblock %}

Company/templates/Company/driver.html
{% extends 'Company/homepage.html' %}
{% load static %}

{% block content_company_page %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="{% static 'Company/javascript/load_division.js' %}"></script>
    <script>
        document.onreadystatechange = function(){
            if (document.readyState === 'interactive') {
                on_load_province();
            }
        } 
    </script>
    <link rel="stylesheet" href="{% static 'Company/css/driver.css' %}">
    {% if new_driver == True %}
        <div class="notification__new__driver">
            <p>Thêm tài xế mới thành công</p>
        </div>
    {% elif new_driver == False %}
        <div class="notification__new__driver">
            <p>Thêm tài xế mới thất bại</p>
        </div>
    {% endif %}
    <form method='post'>
        {% csrf_token %}
        <div class="ins__driver__title">
            <h1>Add New Driver</h1>
            <input type="submit" value="Add New">
        </div><hr>
        <div class="ins__driver__item">
            <label>User name :</label>
            <input type="text" name="input_new_username">
        </div>
        <div class="ins__driver__item">
            <label>Password :</label>
            <input type="password" name="input_new_pass">
        </div>
        <div class="ins__driver__item">
            <label>Full name :</label>
            <input type="text" name="input_new_full_name">
        </div>
        <div class="ins__driver__item">
            <label>Gmail :</label>
            <input type="text" name="input_new_gmail">
        </div>
        <div class="ins__driver__item">
            <label>Telephone :</label>
            <input type="tel" name="input_new_tel">
        </div>
        <div class="ins__driver__item ins__driver__division">
            <div>
                <label>Province :</label>
                <select name="select_new_province" id="choose__province__new__dispatcher" class="new__province__dispatcher__select" onchange="load_district()">
                    <option value="None">Choose Province</option>
                </select>
            </div>
            <div>
                <label>District :</label>
                <select name="select_new_district" id="choose__district__new__dispatcher" onchange="load_ward()">
                    <option value="None">Choose District</option>
                </select>
            </div>
            <div>
                <label>Ward :</label>
                <select name="select_new_ward" id="choose__ward__new__dispatcher">
                    <option value="None">Choose Ward</option>
                </select>
            </div>
        </div>
        <div class="ins__driver__item">
            <label>Gender :</label>
            <select name="ins_new_gender">
                <option value="None">Choose Gender</option>
                <option value="men">Men</option>
                <option value="woman">Woman</option>
                <option value="other">Other</option>
            </select>
        </div>
        <div class="ins__driver__item">
            <label>Level License :</label>
            <select name="ins_new_level_license">
                <option value="None">Choose Level License</option>
                <option value="A1">A1</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
                <option value="E">E</option>
            </select>
        </div>
    </form>
{% endblock %}

Company/templates/Company/homepage.html
{% load static %}

<link rel="stylesheet" href="{% static 'Company/css/homepage.css' %}">
<script src="{% static 'Company/javascript/homepage.js' %}" defer></script>
<div class="side__bar">
    <a href="#" class="side__bar__link active__link">Homepage</a>
    <a href="#" class="side__bar__link">About</a>
    <a href="#" class="side__bar__link">Contact</a>
    <a href="#" class="side__bar__link">Static</a>
    <a href="#" class="side__bar__link">Order</a>
    <button type="button" class="dropdown__btn__employee">Employee</button>
    <div class="employee__dropdown">
        <a href="{% url 'Company_app:Company_sales' %}">Sale</a>
        <a href="{% url 'Company_app:Company_dispatcher' %}">Dispatcher</a>
        <a href="{% url 'Company_app:Company_driver' %}">Driver</a>
    </div>
    <div class="option__link__sidebar">
        <a href="{% url 'Company_app:Company_log_out' %}">Log out</a>
        <p>V 1.0.0</p>
    </div>
</div>

<div class="content__side">
    {% block content_company_page %}

    {% endblock %}
</div>

Company/templates/Company/sale.html
{% extends 'Company/homepage.html' %}
{% load static %}

{% block content_company_page %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="{% static 'Company/javascript/load_division.js' %}"></script>
    <script>
        document.onreadystatechange = function(){
            if (document.readyState === 'interactive') {
                on_load_province();
            }
        } 
    </script>
    <link rel="stylesheet" href="{% static 'Company/css/sale.css' %}">
    {% if ins_sale_mess %}
        <div>
            <p>{{ins_sale_mess}}</p>
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="create__new__sale">
            <div class="new__sale__title">
                <h1>New Sale</h1>
                <input type="submit" value="Add New">
            </div>
            <hr><br>
            <div class="new__sale-item">
                <label>User name :</label>
                <input type="text" name="new_sale_username">
            </div>
            <div class="new__sale-item">
                <label>Password :</label>
                <input type="password" name="new_sale_password">
            </div>
            <div class="new__sale-item">
                <label>Gmail :</label>
                <input type="text" name="new_sale_gmail">
            </div>
            <div class="new__sale-item">
                <label>Telephone :</label>
                <input type="tel" name="new_sale_tel">
            </div>
            <div class="new__sale-item">
                <label>Gender :</label>
                <select name="new_sale_gender">
                    <option value="None">Choose Gender</option>
                    <option value="men">Men</option>
                    <option value="woman">Woman</option>
                    <option value="other">Other</option>
                </select>
            </div>
            <div class="new__sale-item new__sale__division">
                <div>
                    <label>Province :</label>
                    <select name="new_sale_province" id="choose__province__new__dispatcher" class="new__province__dispatcher__select" onchange="load_district()">
                        <option value="None">Choose Province</option>
                    </select>
                </div>
                <div>
                    <label>District :</label>
                    <select name="new_sale_district" id="choose__district__new__dispatcher" onchange="load_ward()">
                        <option value="None">Choose District</option>
                    </select>
                </div>
                <div>
                    <label>Ward :</label>
                    <select name="new_sale_ward" id="choose__ward__new__dispatcher">
                        <option value="None">Choose Ward</option>
                    </select>
                </div>   
            </div>
        </div>
    </form>
{% endblock %}