DT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('Homepage.urls')),
    path('host/', include('Host.urls')),
    path('company/', include('Company.urls')),
    path('sales/', include('Sales.urls')),
    path('dispatcher/', include('Dispatcher.urls')),
    path('driver/', include('Driver.urls'))
]

Dispatcher/urls.py
from django.urls import path

from . import views 

app_name = 'Dispatcher_app'

urlpatterns = [
    path('get-all-province/', views.get_all_province, name = 'Dispatcher_get_all_province'),
    path('get-all-district/', views.get_district_by_province, name = 'Dispatcher_get_all_district'),
    path('get-all-ward/', views.get_ward_by_district_province, name = 'Dispatcher_get_all_ward'),
    path('', views.Homepage.as_view(), name = 'Dispatcher_homepage'),
    path('get-order/', views.Get_order.as_view(), name = 'Dispatcher_get_order'),
    path('get-order/send-order/<str:no_contract>/', views.Send_order.as_view(), name = 'Dispatcher_send_order'),
    path('show-order/', views.Show_order.as_view(), name='Dispatcher_show_order'),
    path('log-out/', views.log_out, name='Dispatcher_log_out')    
]

Dispatcher/models.py
from django.db import models

# Create your models here.

Dispatcher/views.py
import json
from dotenv import load_dotenv
import os
import jwt 
import datetime 

from django.shortcuts import render, redirect
from django.views import View 
from django.http import JsonResponse

from . import  exec_data

# Create your views here.
def check_login_required(token_str):
    load_dotenv()
    secret_key = os.getenv('secret_key')
    decode_token = jwt.decode(token_str, secret_key, algorithms = ["HS256"])
    current_time = datetime.datetime.now()
    end_time_token = datetime.datetime.strptime(decode_token['end_time'], f'%d-%m-%Y %H:%M:%S')
    if current_time < end_time_token:
        role_user_temp = decode_token['role_user']
        if role_user_temp == 'dispatcher':
            return True
        else:
            return 'NP'
    else:
        return 'ET'

# 3 function help to load and get division
def get_all_province(request):
    # Check token
    full_token_str = request.session.get('token_dt2023_web_demo', None)
    if full_token_str is None or full_token_str == '':
        return redirect('Homepage_app:Homepage_homepage')
    check_token_str = check_login_required(full_token_str)
    if check_token_str != True:
        return redirect('Homepage_app:Homepage_homepage')
    # End check token string

    get_all_province = exec_data.get_all_province()
    lst_all_province_temp = [item['province'] for item in get_all_province]
    dict_all_province = {'result' : lst_all_province_temp}
    return JsonResponse(dict_all_province)
    
def get_district_by_province(request):
    # Check token
    full_token_str = request.session.get('token_dt2023_web_demo', None)
    if full_token_str is None or full_token_str == '':
        return redirect('Homepage_app:Homepage_homepage')
    check_token_str = check_login_required(full_token_str)
    if check_token_str != True:
        return redirect('Homepage_app:Homepage_homepage')
    # End check token string

    name_province = request.POST.get('province', None)
    get_all_district = exec_data.get_all_district_by_name_province(name_province)
    lst_all_district = [item['district'] for item in get_all_district]
    dict_all_district = {'result' : lst_all_district}
    return JsonResponse(dict_all_district)

def get_ward_by_district_province(request):
    # Check token
    full_token_str = request.session.get('token_dt2023_web_demo', None)
    if full_token_str is None or full_token_str == '':
        return redirect('Homepage_app:Homepage_homepage')
    check_token_str = check_login_required(full_token_str)
    if check_token_str != True:
        return redirect('Homepage_app:Homepage_homepage')
    # End check token string

    name_province = request.POST.get('province', None)
    name_district = request.POST.get('district', None)
    get_all_ward = exec_data.get_all_ward_by_name_province_name_district(name_province, name_district)
    lst_all_ward = [item['ward'] for item in get_all_ward]
    dict_all_ward = {'result' : lst_all_ward}
    return JsonResponse(dict_all_ward)

def log_out(request):
    request.session.clear()
    return redirect('Homepage_app:Homepage_homepage')

class Homepage(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Dispatcher/base_page.html')
    
class Get_order(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_dispatcher = request.session.get('id_role_user_dt2023')
        get_all_customer = exec_data.get_all_customer_by_id_company(id_dispatcher)

        context_return = {}
        if get_all_customer != False:
            context_return['all_customer'] = get_all_customer
        else:
            context_return['all_customer'] = False

        context_return['all_contract'] = False
        return render(request, 'Dispatcher/get_order.html', context_return)
    def post(self, request):
        id_dispatcher = request.session.get('id_role_user_dt2023')
        get_all_customer = exec_data.get_all_customer_by_id_company(id_dispatcher)

        new_id_customer = None
        for index in get_all_customer:
            new_id_customer_temp = request.POST.get(f'input_submit_{index["id"]}', None)
            if new_id_customer_temp is not None:
                new_id_customer = index["id"]
            
        get_all_contract = exec_data.get_all_contract_by_id_customer(new_id_customer)

        context_return = {}

        if get_all_contract != False:
            context_return['all_contract'] = get_all_contract
        else:
            context_return['all_contract'] = False

        if get_all_customer != False:
            context_return['all_customer'] = get_all_customer
        else:
            context_return['all_customer'] = False

        return render(request, 'Dispatcher/get_order.html', context_return)

class Send_order(View):
    def get(self, request, no_contract):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_dispatcher = request.session.get('id_role_user_dt2023', None)
        get_all_driver = exec_data.get_all_driver_by_id_dispatcher(id_dispatcher)
        context_return = {}

        if get_all_driver != False:
            context_return['all_driver'] = get_all_driver
        else:
            context_return['msg_load'] = False

        return render(request, 'Dispatcher/send_order.html', context_return)
    def post(self, request, no_contract):
        id_dispatcher = request.session.get('id_role_user_dt2023', None)
        get_all_driver = exec_data.get_all_driver_by_id_dispatcher(id_dispatcher)
        
        new_province_sender = request.POST.get('get_province_sender', None)
        new_district_sender = request.POST.get('get_district_sender', None)
        new_ward_sender = request.POST.get('get_ward_sender', None)
        new_type_sender = request.POST.get('get_type_sender', None)

        new_province_receiver = request.POST.get('get_province_receiver', None)
        new_district_receiver = request.POST.get('get_district_receiver', None)
        new_ward_receiver = request.POST.get('get_ward_receiver', None)
        new_type_receiver = request.POST.get('get_type_receiver', None)

        new_id_driver = request.POST.get('get_driver_select', None)
        new_departure_time = request.POST.get('get_departure_time', None)
        new_estimate_time = request.POST.get('get_estimate_time', None)
        new_note = request.POST.get('get_note', None)
        new_real_time_arrive = request.POST.get('get_real_time', None)

        new_list_product = request.POST.get('input_list_product', None)
        new_list_product = json.loads(new_list_product)

        return_order = {'no_contract_para' : no_contract, 'province_sender_para' : new_province_sender, 'district_sender_para' : new_district_sender, 'ward_sender_para' : new_ward_sender, 'province_receiver_para' : new_province_receiver, 'district_receiver_para' : new_district_receiver, 'ward_receiver_para' : new_ward_receiver, 'id_driver_para' : new_id_driver, 'departure_time_para' : new_departure_time, 'estimate_time_arrive_para' : new_estimate_time, 'note_para' : new_note, 'real_time_arrive_para' : new_real_time_arrive, 'type_sender_para' : new_type_sender, 'type_receiver_para' : new_type_receiver, 'new_list_product_para' : new_list_product}

        context_return = {}

        ins_new_order = exec_data.ins_new_order(**return_order)
        
        if ins_new_order != False:
            context_return['new_order_status'] = f'Tạo đơn hàng thành công. Mã đơn hàng là {ins_new_order}'
        else:
            context_return['new_order_status'] = False

        if get_all_driver != False:
            context_return['all_driver'] = get_all_driver
        else:
            context_return['msg_load'] = False

        return render(request, 'Dispatcher/send_order.html', context_return)

class Show_order(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_dispatcher = request.session.get('id_role_user_dt2023', None)

        all_order = exec_data.show_all_order_by_id_company(id_dispatcher)
        context_return = {}

        if all_order != False:
            context_return['all_order'] = all_order
        else:
            context_return['all_order'] = False

        return render(request, 'Dispatcher/show_order.html', context_return)

Dispatcher/templates/Dispatcher/base_page.html
{% load static %}

<link rel="stylesheet" href="{% static 'Dispatcher/css/base_page.css' %}">
<header>
    <div class="header__inner">
        <div class="header__item">
            <p>Hello, ABC</p>
        </div>
        <div class="header__item">
            <a href="{% url 'Dispatcher_app:Dispatcher_get_order' %}" class="header__item__link">Tiếp nhận đơn hàng</a>
            <a href="{% url 'Dispatcher_app:Dispatcher_show_order' %}" class="header__item__link">Đơn hàng</a>
            <a href="{% url 'Dispatcher_app:Dispatcher_log_out' %}">Đăng xuất</a>
        </div>
    </div>
</header>
<div class="content__base__page">
    {% block content_dispatcher %}

    {% endblock %}
</div>

Dispatcher/templates/Dispatcher/get_order.html
{% extends 'Dispatcher/base_page.html' %}
{% load static %}

{% block content_dispatcher %}
    <link rel="stylesheet" href="{% static 'Dispatcher/css/get_order.css' %}">
    {% if all_contract != False %}
        {% if all_contract|length > 0 %}
            <br>
            <h1>Found {{all_contract|length}} contract.</h1>
            <div class="show__all__contract-customer">
                <table>
                    <tr>
                        <th>No.</th>
                        <th>Start time</th>
                        <th>End time</th>
                        <th>No contract</th>
                        <th>Send Order</th>
                    </tr>
                    {% for contract in all_contract %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{contract.start_time}}</td>
                            <td>{{contract.end_time}}</td>
                            <td>{{contract.no_contract}}</td>
                            <td>
                                <a href="{% url 'Dispatcher_app:Dispatcher_send_order' contract.no_contract %}">Send order</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <br><hr><br>
        {% else %}
            <p>Không tìm được hợp đồng nào đang trong trạng thái cần giao hàng</p><br><hr><br>
        {% endif %}
        
    {% endif %}

    {% if all_customer %}
        <table>
            <tr>
                <th>No.</th>
                <th>Telephone Number</th>
                <th>Gmail</th>
                <th>Country</th>
                <th>Province</th>
                <th>District</th>
                <th>Ward</th>
                <th>Watch Contract</th>
            </tr>
            {% for customer in all_customer %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{customer.tel}}</td>
                    <td>{{customer.gmail}}</td>
                    <td>{{customer.country}}</td>
                    <td>{{customer.province}}</td>
                    <td>{{customer.district}}</td>
                    <td>{{customer.ward}}</td>
                    <td>
                        <form method="post">
                            {% csrf_token %}
                            <input type="submit" value="Watch" name="input_submit_{{customer.id}}">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>{{all_customer}}</p>
    {% endif %}
{% endblock %}

Dispatcher/templates/Dispatcher/send_order.html
{% extends 'Dispatcher/base_page.html' %}
{% load static %}

{% block content_dispatcher %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'Dispatcher/css/send_order.css' %}">
    <script src="{% static 'Dispatcher/javascript/send_order.js' %}"></script>
    <script>
        document.onreadystatechange = function(){
            if (document.readyState === 'interactive') {
                on_load_province();
                on_load_province_receiver()
            }
        } 
    </script>
    {% if new_order_status == True %}
        <div class="success__new__order status_new_order">
            <p>{{new_order_status}}</p>
        </div>
    {% elif new_order_status == False %}
        <div class="fail__new__order status_new_order">
            <p>{{new_order_status}}</p>
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="form__item get__division">
            <div>
                <label>Province :</label>
                <select name="get_province_sender" class="select__province__sender" id="choose__province__sender" onchange="load_district()">
                    <option value="None">Choose Province</option>
                </select>
            </div>
            <div>
                <label>District :</label>
                <select name="get_district_sender" id = "choose__district__sender" onchange="load_ward()">
                    <option value="None">Choose District</option>
                </select>
            </div>
            <div>
                <label>Ward :</label>
                <select name="get_ward_sender" id="choose__ward__sender">
                    <option value="None">Choose Ward</option>
                </select>
            </div>
            <div>
                <label>Type :</label>
                <select name="get_type_sender">
                    <option value="home">Home</option>
                    <option value="company">Company</option>
                </select>
            </div>
        </div>
        <div class="form__item get__division">
            <div>
                <label>Province :</label>
                <select name="get_province_receiver" class="select__province__receiver" id="choose__province__receiver" onchange="load_district_receiver()">
                    <option value="None">Choose Province</option>
                </select>
            </div>
            <div>
                <label>District :</label>
                <select name="get_district_receiver" id = "choose__district__receiver" onchange="load_ward_receiver()">
                    <option value="None">Choose District</option>
                </select>
            </div>
            <div>
                <label>Ward :</label>
                <select name="get_ward_receiver" id="choose__ward__receiver">
                    <option value="None">Choose Ward</option>
                </select>
            </div>
            <div>
                <label>Type :</label>
                <select name="get_type_receiver">
                    <option value="home">Home</option>
                    <option value="company">Company</option>
                </select>
            </div>
        </div>
        <div class="form__item">
            <label>Choose Driver :</label>
            <select name="get_driver_select">
                <option value="None">Choose Driver</option>
                {% for driver in all_driver %}
                    <option value="{{driver.id}}">Full name : {{driver.full_name}}; ID Driver : {{driver.id_driver}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form__item">
            <label>Departure Time :</label>
            <input type="datetime-local" name="get_departure_time">
        </div>
        <div class="form__item">
            <label>Estimate Time :</label>
            <input type="datetime-local" name="get_estimate_time">
        </div>
        <div class="form__item">
            <label>Note :</label>
            <textarea name="get_note"></textarea>
        </div>
        <div class="form__item">
            <label>Real Time Arrive :</label>
            <input type="datetime-local" name="get_real_time">
        </div>
        <div class="form__list__product">
            <h1>Add Product</h1>
            <div class="add__list__product">
                <div>
                    <label>Name :</label>
                    <input type="text" name="add_name_product" id="name__product__input__id">
                </div>
                <div>
                    <label>Quantity :</label>
                    <input type="number" name="add_quantity_product" id ="quantity__product__input__id">
                </div>
                <button type="button" onclick="add_product_to_list_product()">Add Product</button>
            </div><br><hr><br>
            <div class="show__list__product">
                <table id="show__list__product__id">
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Quantity</th>
                    </tr>
                </table>
            </div>
        </div><br>
        <input type="text" id="list__product__value" value="{}" name="input_list_product" hidden>
        <input type="submit" value = 'Send'>
    </form>
{% endblock %}

Dispatcher/templates/Dispatcher/show_order.html
{% extends 'Dispatcher/base_page.html' %}
{% load static %}

{% block content_dispatcher %}
    <link rel="stylesheet" href="{% static 'Dispatcher/css/show_order.css' %}">
    {% if all_order %}
        {% if all_order|length == 0 %}
            <p>Không có đơn hàng nào </p>
        {% else %}
            <table>
                <tr>
                  <th>No.</th>
                  <th>Code Order</th>
                  <th>Departure Time</th>
                  <th>Estimate Time</th>
                  <th>Status</th>  
                </tr>
                {% for order in all_order %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{order.code_order}}</td>
                        <td>{{order.departure_time}}</td>
                        <td>{{order.estimate_time_arrive}}</td>
                        <td>{{order.status}}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    {% endif %}
{% endblock %}