DT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('Homepage.urls')),
    path('host/', include('Host.urls')),
    path('company/', include('Company.urls')),
    path('sales/', include('Sales.urls')),
    path('dispatcher/', include('Dispatcher.urls')),
    path('driver/', include('Driver.urls'))
]

Driver/urls.py
from django.urls import path

from . import views 

app_name = 'Driver_app'

urlpatterns = [
    path('', views.Base_page.as_view(), name = 'Driver_base_page'),
    path('log-out/', views.log_out, name = 'Driver_log_out'),
    path('order-need-delivery/', views.Order_need_delivery.as_view(), name = 'Driver_order_need_delivery'),
    path('update-status-order/', views.Update_status_order.as_view(), name='Driver_update_status_order'),
    path('order-in-delivery/', views.Order_in_delivery.as_view(), name='Driver_order_in_delivery'),
    path('order-success/', views.Order_success.as_view(), name='Driver_order_success')
]

Driver/models.py
from django.db import models

# Create your models here.

Driver/views.py
from dotenv import load_dotenv
import os
import jwt 
import datetime 

from django.shortcuts import render, redirect
from django.views import View 

from . import exec_data
# Create your views here.
# This function try to check token. If token already is use. It continue browsing or redirect to homepage
def check_login_required(token_str):
    load_dotenv()
    secret_key = os.getenv('secret_key')
    decode_token = jwt.decode(token_str, secret_key, algorithms = ["HS256"])
    current_time = datetime.datetime.now()
    end_time_token = datetime.datetime.strptime(decode_token['end_time'], f'%d-%m-%Y %H:%M:%S')
    if current_time < end_time_token:
        role_user_temp = decode_token['role_user']
        if role_user_temp == 'driver':
            return True
        else:
            return 'NP'
    else:
        return 'ET'

def log_out(request):
    request.session.clear()
    return redirect('Homepage_app:Homepage_homepage')

class Base_page(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Driver/base_page.html')

class Order_need_delivery(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_driver = request.session.get('id_role_user_dt2023', None)
        
        all_order_need_delivery = exec_data.get_all_order_need_delivery(id_driver)
        context_return = {'all_order_need_delivery' : all_order_need_delivery}
        return render(request, 'Driver/order_need_delivery.html', context_return)

class Update_status_order(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        return render(request, 'Driver/update_status_order.html')
    def post(self, request):
        get_code_order = request.POST.get('input_code_order', None)
        get_status_update = request.POST.get('select_status_order', None)

        context_return = {}
        update_status_order = exec_data.update_status_order_by_code_order(get_code_order, get_status_update)

        if update_status_order == True:
            context_return['notification_update_status'] = True
            context_return['msg_update_status'] = f'Cập nhật đơn hàng "{get_code_order}" với trạng thái "{get_status_update}" thành công'
        else:
            context_return['notification_update_status'] = False
            context_return['msg_update_status'] = f'Cập nhật đơn hàng "{get_code_order}" với trạng thái "{get_status_update}" thất bại'
        return render(request, 'Driver/update_status_order.html', context_return)

class Order_in_delivery(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_driver = request.session.get('id_role_user_dt2023', None)

        all_order_in_delivery = exec_data.get_all_order_in_delivery(id_driver)
        context_return = {'all_order_in_delivery' : all_order_in_delivery}
        return render(request, 'Driver/order_in_delivery.html', context_return)

class Order_success(View):
    def get(self, request):
        # Check token
        full_token_str = request.session.get('token_dt2023_web_demo', None)
        if full_token_str is None or full_token_str == '':
            return redirect('Homepage_app:Homepage_homepage')
        check_token_str = check_login_required(full_token_str)
        if check_token_str != True:
            return redirect('Homepage_app:Homepage_homepage')
        # End check token string

        id_driver = request.session.get('id_role_user_dt2023', None)

        all_order_success = exec_data.get_all_order_success(id_driver)
        context_return = {'all_order_success' : all_order_success}
        return render(request, 'Driver/order_success.html', context_return)

Driver/templates/Driver/base_page.html
{% load static %}

<link rel="stylesheet" href="{% static 'Driver/css/base_page.css' %}">
<header>
    <div class="header__inner">
        <div>
            <p>Hello, ABC</p>
        </div>
        <div>
            <a href="{% url 'Driver_app:Driver_order_need_delivery' %}" class="header__links">Đơn hàng cần giao</a>
            <a href="{% url 'Driver_app:Driver_order_in_delivery' %}" class="header__links">Đơn hàng đang giao</a>
            <a href="{% url 'Driver_app:Driver_order_success' %}" class="header__links">Đơn hàng giao thành công</a>
            <a href="{% url 'Driver_app:Driver_update_status_order' %}" class="header__links">Cập nhật trạng thái đơn hàng</a>
            <a href="{% url 'Driver_app:Driver_log_out' %}" class="header__links">Đăng xuất</a>
        </div>
    </div>
</header>
<div class="content_driver_page">
    {% block content_driver_page %}

    {% endblock %}
</div>

Driver/templates/Driver/order_in_delivery.html
{% extends 'Driver/base_page.html' %}
{% load static %}

{% block content_driver_page %}
    <link rel="stylesheet" href="{% static 'Driver/css/status_order.css' %}">
    <table>
        <tr>
            <th>No.</th>
            <th>Code order</th>
            <th>Date Create</th>
            <th>Departure Time</th>
            <th>Estimate Time</th>
            <th>Status</th>
        </tr>
        {% for order in all_order_in_delivery %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{order.code_order}}</td>
                <td>{{order.date_create}}</td>
                <td>{{order.departure_time}}</td>
                <td>{{order.departure_time}}</td>
                <td>{{order.status}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

Driver/templates/Driver/order_need_delivery.html
{% extends 'Driver/base_page.html' %}
{% load static %}

{% block content_driver_page %}
    <link rel="stylesheet" href="{% static 'Driver/css/status_order.css' %}">
    <table>
        <tr>
            <th>No.</th>
            <th>Code order</th>
            <th>Date Create</th>
            <th>Departure Time</th>
            <th>Estimate Time</th>
            <th>Status</th>
        </tr>
        {% for order in all_order_need_delivery %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{order.code_order}}</td>
                <td>{{order.date_create}}</td>
                <td>{{order.departure_time}}</td>
                <td>{{order.departure_time}}</td>
                <td>{{order.status}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

Driver/templates/Driver/order_success.html
{% extends 'Driver/base_page.html' %}
{% load static %}

{% block content_driver_page %}
    <link rel="stylesheet" href="{% static 'Driver/css/status_order.css' %}">
    <table>
        <tr>
            <th>No.</th>
            <th>Code order</th>
            <th>Date Create</th>
            <th>Departure Time</th>
            <th>Estimate Time</th>
            <th>Status</th>
        </tr>
        {% for order in all_order_success %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{order.code_order}}</td>
                <td>{{order.date_create}}</td>
                <td>{{order.departure_time}}</td>
                <td>{{order.departure_time}}</td>
                <td>{{order.status}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

Driver/templates/Driver/update_status_order.html
{% extends 'Driver/base_page.html' %}
{% load static %}

{% block content_driver_page %}
    <link rel="stylesheet" href="{% static 'Driver/css/status_order.css' %}">
    <div class="update__status__item">
        <form method="post">
            {% csrf_token %}
            <label>Input Code Order :</label>
            <input type="text" name="input_code_order">
            <select name="select_status_order">
                <option value="None">Choose Status</option>
                <option value="Delivery">Delivery</option>
                <option value="Success">Success</option>
                <option value="Cancel">Cancel</option>
            </select>
            <input type="submit" value="Update">
        </form>
    </div>

    {% if notification_update_status %}
        <div class="notification__update__status">
            <p>{{msg_update_status}}</p>
        </div>
    {% endif %}
{% endblock %}